### ISSUE TITLE
PyTorch to LinAlg lowering fails for Resnet50

### ISSUE THREAD

**Issue by kumardeepakamd** [nod-ai/SHARK-Turbine#379]
**Error:**
resnet50.fp32.pytorch.torch.mlir:26:13: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %10:3 = torch.operator "torch.aten._native_batch_norm_legit_no_training"(%5, %6, %7, %8, %9, %float1.000000e-01, %float1.000000e-05) : (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.float, !torch.float) -> (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[0],f32>, !torch.vtensor<[0],f32>)
            ^
resnet50.fp32.pytorch.torch.mlir:26:13: note: see current operation: %284:3 = "torch.operator"(%283, %271, %270, %269, %268, %267, %266) <{name = "torch.aten._native_batch_norm_legit_no_training"}> : (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.float, !torch.float) -> (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[0],f32>, !torch.vtensor<[0],f32>)

**Steps to Reproduce**
Save following file as model.py (install any missing pip dependencies in your python virtual environment)
```
import torch
import torch_mlir
from torchvision.models import resnet50, ResNet50_Weights

# Fx importer related
from typing import Optional
import torch.export
from torch_mlir.extras.fx_importer import FxImporter
from torch_mlir import ir
from torch_mlir.dialects import torch as torch_d


weights = ResNet50_Weights.DEFAULT
model = resnet50(weights=weights)
model.eval()

test_input = test_input = torch.randn(1, 3, 224, 224)
test_output = model(test_input)
print("Input:", test_input)
print("Output:", test_output)


def export_and_import(
    f,
    *args,
    fx_importer: Optional[FxImporter] = None,
    constraints: Optional[torch.export.Constraint] = None,
    **kwargs,
):
    context = ir.Context()
    torch_d.register_dialect(context)

    if fx_importer is None:
        fx_importer = FxImporter(context=context)
    prog = torch.export.export(f, args, kwargs, constraints=constraints)
    fx_importer.import_frozen_exported_program(prog)
    return fx_importer.module_op


torch_mlir_model = export_and_import(model, test_input)
with open("resnet50.torch.mlir", "w+") as f:
    f.write(torch_mlir_model.operation.get_asm())

```
Then run:
```<your iree build>/tools/iree-compile --iree-hal-target-backends=llvm-cpu resnet50.torch.mlir > resnet50.fp32.vfmb
```

**Comment by kumardeepakamd** [comment]
resolved

**Comment by saienduri** [comment]
This will also be resolved with https://github.com/llvm/torch-mlir/pull/2879

**Comment by kumardeepakamd** [comment]
Still getting error: 
resnet50.default.pytorch.torch.mlir:26:13: error: failed to legalize operation 'torch.operator' that was explicitly marked illegal
    %10:3 = torch.operator "torch.aten._native_batch_norm_legit_no_training"(%5, %6, %7, %8, %9, %float1.000000e-01, %float1.000000e-05) : (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.float, !torch.float) -> (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[0],f32>, !torch.vtensor<[0],f32>)
            ^
resnet50.default.pytorch.torch.mlir:26:13: note: see current operation: %284:3 = "torch.operator"(%283, %271, %270, %269, %268, %267, %266) <{name = "torch.aten._native_batch_norm_legit_no_training"}> : (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.vtensor<[64],f32>, !torch.float, !torch.float) -> (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[0],f32>, !torch.vtensor<[0],f32>)

**Comment by stellaraccident** [comment]
Decomp not kicking in
